{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "75ee3905",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: google-generativeai in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (0.5.0)\n",
      "Requirement already satisfied: pydantic in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.7.0)\n",
      "Requirement already satisfied: protobuf in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (4.25.3)\n",
      "Requirement already satisfied: google-api-python-client in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.125.0)\n",
      "Requirement already satisfied: tqdm in c:\\programdata\\anaconda3\\lib\\site-packages (from google-generativeai) (4.64.0)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.29.0)\n",
      "Requirement already satisfied: google-ai-generativelanguage==0.6.1 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (0.6.1)\n",
      "Requirement already satisfied: google-api-core in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.18.0)\n",
      "Requirement already satisfied: typing-extensions in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (4.11.0)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-ai-generativelanguage==0.6.1->google-generativeai) (1.23.0)\n",
      "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-api-core->google-generativeai) (2.27.1)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-core->google-generativeai) (1.63.0)\n",
      "Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-core->google-generativeai) (1.62.1)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-core->google-generativeai) (1.62.1)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (4.7.2)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (4.2.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\\programdata\\anaconda3\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.4.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2.0.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (1.26.9)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2021.10.8)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-python-client->google-generativeai) (4.1.1)\n",
      "Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-python-client->google-generativeai) (0.22.0)\n",
      "Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-python-client->google-generativeai) (0.2.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\\programdata\\anaconda3\\lib\\site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai) (3.0.4)\n",
      "Requirement already satisfied: pydantic-core==2.18.1 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from pydantic->google-generativeai) (2.18.1)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from pydantic->google-generativeai) (0.6.0)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from tqdm->google-generativeai) (0.4.4)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install google-generativeai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f3e55227",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\\\Users\\\\Hikaru\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\google\\\\~upb\\\\_message.cp39-win_amd64.pyd'\n",
      "Check the permissions.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Collecting protobuf==3.20\n",
      "  Downloading protobuf-3.20.0-cp39-cp39-win_amd64.whl (904 kB)\n",
      "Installing collected packages: protobuf\n",
      "  Attempting uninstall: protobuf\n",
      "    Found existing installation: protobuf 4.25.3\n",
      "    Uninstalling protobuf-4.25.3:\n",
      "      Successfully uninstalled protobuf-4.25.3\n"
     ]
    }
   ],
   "source": [
    "pip install protobuf==3.20\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3e2cdc30",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting replicate\n",
      "  Downloading replicate-0.25.1-py3-none-any.whl (39 kB)\n",
      "Collecting httpx<1,>=0.21.0\n",
      "  Downloading httpx-0.27.0-py3-none-any.whl (75 kB)\n",
      "Requirement already satisfied: pydantic>1.10.7 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from replicate) (2.7.0)\n",
      "Requirement already satisfied: packaging in c:\\programdata\\anaconda3\\lib\\site-packages (from replicate) (21.3)\n",
      "Requirement already satisfied: typing-extensions>=4.5.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from replicate) (4.11.0)\n",
      "Requirement already satisfied: sniffio in c:\\programdata\\anaconda3\\lib\\site-packages (from httpx<1,>=0.21.0->replicate) (1.2.0)\n",
      "Requirement already satisfied: anyio in c:\\programdata\\anaconda3\\lib\\site-packages (from httpx<1,>=0.21.0->replicate) (3.5.0)\n",
      "Requirement already satisfied: idna in c:\\programdata\\anaconda3\\lib\\site-packages (from httpx<1,>=0.21.0->replicate) (3.3)\n",
      "Requirement already satisfied: certifi in c:\\programdata\\anaconda3\\lib\\site-packages (from httpx<1,>=0.21.0->replicate) (2021.10.8)\n",
      "Collecting httpcore==1.*\n",
      "  Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)\n",
      "Collecting h11<0.15,>=0.13\n",
      "  Downloading h11-0.14.0-py3-none-any.whl (58 kB)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from pydantic>1.10.7->replicate) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.18.1 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from pydantic>1.10.7->replicate) (2.18.1)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\\programdata\\anaconda3\\lib\\site-packages (from packaging->replicate) (3.0.4)\n",
      "Installing collected packages: h11, httpcore, httpx, replicate\n",
      "Successfully installed h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 replicate-0.25.1\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "  WARNING: The script httpx.exe is installed in 'C:\\Users\\Hikaru\\AppData\\Roaming\\Python\\Python39\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "pip install replicate\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5abc9824",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "ERROR: Could not find a version that satisfies the requirement os (from versions: none)\n",
      "ERROR: No matching distribution found for os\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rotobuf (c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "pip install os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d622522",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [15/Apr/2024 12:27:58] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Apr/2024 12:38:45] \"POST /main HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Apr/2024 12:38:47] \"POST /text HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Apr/2024 12:38:57] \"POST /text_reply HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Apr/2024 12:39:03] \"POST /main HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [15/Apr/2024 12:39:05] \"POST /end HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "for gracefully ended\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask,request,render_template\n",
    "import google.generativeai as palm\n",
    "import replicate\n",
    "import os\n",
    "\n",
    "os.environ[\"REPLICATE_API_TOKEN\"] = \"r8_PgWv9pc0H0ITuiG96E5M6E8jWuFz4Zy1aZqMA\"\n",
    "\n",
    "model = {\n",
    "    \"model\": \"models/chat-bison-001\"\n",
    "}\n",
    "palm.configure(api_key=\"AIzaSyCvbHTFA28n-7zTNxVrAbCPIKsSiMSJWEo\")\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "name=\"\"\n",
    "flag=1\n",
    "\n",
    "@app.route(\"/\",methods=[\"GET\",\"POST\"])\n",
    "def index():\n",
    "    return(render_template(\"index.html\"))\n",
    "\n",
    "@app.route(\"/main\",methods=[\"GET\",\"POST\"])\n",
    "def main():\n",
    "    global name,flag\n",
    "    if flag==1:\n",
    "        name = request.form.get(\"q\")\n",
    "        flag=0\n",
    "    return(render_template(\"main.html\",r=name))\n",
    "\n",
    "@app.route(\"/text\",methods=[\"GET\",\"POST\"])\n",
    "def text():\n",
    "    return(render_template(\"text.html\"))\n",
    "\n",
    "@app.route(\"/text_reply\",methods=[\"GET\",\"POST\"])\n",
    "def text_reply():\n",
    "    q = request.form.get(\"q\")\n",
    "    r = palm.chat(**model, messages=q)\n",
    "    return(render_template(\"text_reply.html\",r=r.last))\n",
    "\n",
    "\n",
    "@app.route(\"/image\",methods=[\"GET\",\"POST\"])\n",
    "def image():\n",
    "    return(render_template(\"image.html\"))\n",
    "\n",
    "@app.route(\"/image_reply\",methods=[\"GET\",\"POST\"])\n",
    "def image_reply():\n",
    "    q = request.form.get(\"q\")\n",
    "    r = replicate.run(\n",
    "        \"stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf\",\n",
    "        input={\n",
    "            \"prompt\": q,\n",
    "        }\n",
    "    )\n",
    "    return(render_template(\"image_reply.html\",r=r[0]))\n",
    "\n",
    "@app.route(\"/music\",methods=[\"GET\",\"POST\"])\n",
    "def music():\n",
    "    return(render_template(\"music.html\"))\n",
    "\n",
    "@app.route(\"/music_reply\",methods=[\"GET\",\"POST\"])\n",
    "def music_reply():\n",
    "    q = request.form.get(\"q\")\n",
    "    r = replicate.run(\n",
    "        \"meta/musicgen:7be0f12c54a8d033a0fbd14418c9af98962da9a86f5ff7811f9b3423a1f0b7d7\",\n",
    "        input={\n",
    "            \"prompt\": q,\n",
    "            \"duration\":5\n",
    "        }\n",
    "    )\n",
    "    return(render_template(\"music_reply.html\",r=r))\n",
    "\n",
    "@app.route(\"/video\",methods=[\"GET\",\"POST\"])\n",
    "def video():\n",
    "    return(render_template(\"video.html\"))\n",
    "\n",
    "@app.route(\"/video_reply\",methods=[\"GET\",\"POST\"])\n",
    "def video_reply():\n",
    "    q = request.form.get(\"q\")\n",
    "    r = replicate.run(\n",
    "        \"anotherjesse/zeroscope-v2-xl:9f747673945c62801b13b84701c783929c0ee784e4748ec062204894dda1a351\",\n",
    "        input={\n",
    "            \"prompt\": q,\n",
    "            \"num_frames\":10\n",
    "        }\n",
    "    )\n",
    "    return(render_template(\"video_reply.html\",r=r[0]))\n",
    "           \n",
    "@app.route(\"/end\",methods=[\"GET\",\"POST\"])\n",
    "def end():\n",
    "    global flag\n",
    "    print(\"for gracefully ended\")\n",
    "    flag=1\n",
    "    return(render_template(\"index.html\"))\n",
    "    \n",
    "if __name__ == \"__main__\":\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "2a9b63af",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: google-generativeai in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (0.5.0)\n",
      "Requirement already satisfied: google-api-python-client in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.125.0)\n",
      "Requirement already satisfied: protobuf in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (4.25.3)\n",
      "Requirement already satisfied: google-api-core in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.18.0)\n",
      "Requirement already satisfied: google-ai-generativelanguage==0.6.1 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (0.6.1)\n",
      "Requirement already satisfied: tqdm in c:\\programdata\\anaconda3\\lib\\site-packages (from google-generativeai) (4.64.0)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.29.0)\n",
      "Requirement already satisfied: pydantic in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (2.7.0)\n",
      "Requirement already satisfied: typing-extensions in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-generativeai) (4.11.0)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-ai-generativelanguage==0.6.1->google-generativeai) (1.23.0)\n",
      "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-api-core->google-generativeai) (2.27.1)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-core->google-generativeai) (1.63.0)\n",
      "Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-core->google-generativeai) (1.62.1)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-core->google-generativeai) (1.62.1)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (4.7.2)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from google-auth>=2.15.0->google-generativeai) (4.2.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\\programdata\\anaconda3\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.4.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (1.26.9)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2021.10.8)\n",
      "Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-python-client->google-generativeai) (0.22.0)\n",
      "Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-python-client->google-generativeai) (0.2.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from google-api-python-client->google-generativeai) (4.1.1)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\\programdata\\anaconda3\\lib\\site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai) (3.0.4)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from pydantic->google-generativeai) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.18.1 in c:\\users\\hikaru\\appdata\\roaming\\python\\python39\\site-packages (from pydantic->google-generativeai) (2.18.1)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from tqdm->google-generativeai) (0.4.4)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install google-generativeai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "769bdd89",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
